#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /login/login_check
  methods: [POST]

gesident_jwt__refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh